#!/usr/bin/env python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-p', '--pressure', type=float)
parser.add_argument('--kT', type=float)
parser.add_argument('-N', type=int)
args = parser.parse_args()
print(args.N * args.kT / args.pressure)
